package com.example.zaixiantiku.controller;

import com.example.zaixiantiku.common.annotation.OperationLog;
import com.example.zaixiantiku.common.Result;
import com.example.zaixiantiku.pojo.dto.PaperAutoGenerateDTO;
import com.example.zaixiantiku.pojo.dto.PaperSaveDTO;
import com.example.zaixiantiku.pojo.vo.PageResult;
import com.example.zaixiantiku.pojo.vo.PaperVO;
import com.example.zaixiantiku.service.PaperService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/papers")
@RequiredArgsConstructor
@Tag(name = "试卷管理", description = "试卷创建/自动生成/列表/详情")
public class PaperController {

    private final PaperService paperService;

    @GetMapping
    @PreAuthorize("hasAnyRole('ADMIN','TEACHER')")
    @Operation(summary = "分页查询试卷列表")
    public Result<PageResult<PaperVO>> getPaperPage(
            @RequestParam(defaultValue = "1") Integer page,
            @RequestParam(defaultValue = "10") Integer size,
            @RequestParam(required = false) String keyword,
            @RequestParam(required = false) Long courseId,
            @RequestParam(required = false) Integer status) {
        PageResult<PaperVO> res = paperService.getPaperPage(page, size, keyword, courseId, status);
        return Result.success(res);
    }

    @GetMapping("/{id}")
    @PreAuthorize("hasAnyRole('ADMIN','TEACHER')")
    @Operation(summary = "获取试卷详情")
    public Result<PaperVO> getPaperDetail(@PathVariable("id") Long id) {
        PaperVO vo = paperService.getPaperDetail(id);
        return Result.success(vo);
    }

    @PostMapping
    @PreAuthorize("hasAnyRole('ADMIN','TEACHER')")
    @OperationLog(module = "试卷管理", operation = "手动组卷")
    @Operation(summary = "手动组卷")
    public Result<PaperVO> createPaper(@RequestBody PaperSaveDTO saveDTO) {
        PaperVO vo = paperService.createPaper(saveDTO);
        return Result.success(vo);
    }

    @PutMapping("/{id}")
    @PreAuthorize("hasAnyRole('ADMIN','TEACHER')")
    @OperationLog(module = "试卷管理", operation = "修改试卷")
    @Operation(summary = "修改试卷")
    public Result<PaperVO> updatePaper(@PathVariable("id") Long id, @RequestBody PaperSaveDTO saveDTO) {
        PaperVO vo = paperService.updatePaper(id, saveDTO);
        return Result.success(vo);
    }

    @PostMapping("/auto-generate")
    @PreAuthorize("hasAnyRole('ADMIN','TEACHER')")
    @OperationLog(module = "试卷管理", operation = "自动组卷")
    @Operation(summary = "自动组卷")
    public Result<PaperVO> autoGeneratePaper(@RequestBody PaperAutoGenerateDTO generateDTO) {
        PaperVO vo = paperService.autoGeneratePaper(generateDTO);
        return Result.success(vo);
    }

    @DeleteMapping("/{id}")
    @PreAuthorize("hasAnyRole('ADMIN','TEACHER')")
    @OperationLog(module = "试卷管理", operation = "删除试卷")
    @Operation(summary = "删除试卷")
    public Result<Void> deletePaper(@PathVariable("id") Long id) {
        paperService.deletePaper(id);
        return Result.success(1, "删除成功", null);
    }
}
