package com.example.zaixiantiku.service;

import com.example.zaixiantiku.pojo.dto.PaperAutoGenerateDTO;
import com.example.zaixiantiku.pojo.dto.PaperSaveDTO;
import com.example.zaixiantiku.pojo.vo.PageResult;
import com.example.zaixiantiku.pojo.vo.PaperVO;

public interface PaperService {
    PaperVO createPaper(PaperSaveDTO saveDTO);

    PaperVO autoGeneratePaper(PaperAutoGenerateDTO generateDTO);
    PageResult<PaperVO> getPaperPage(Integer page, Integer size, String keyword, Long courseId, Integer status);
    void deletePaper(Long id);
    PaperVO updatePaper(Long id, PaperSaveDTO saveDTO);
    PaperVO getPaperDetail(Long id);
}
