package com.example.zaixiantiku.pojo.dto;

import lombok.Data;

@Data
public class PaperAutoGenerateDTO {
    private String paperName;
    private Long courseId;
    private Integer totalScore;
    private AutoGenerateRuleDTO rule;
}
