package com.example.zaixiantiku.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.example.zaixiantiku.entity.CourseTeacher;
import com.example.zaixiantiku.entity.Paper;
import com.example.zaixiantiku.entity.PaperQuestion;
import com.example.zaixiantiku.entity.Question;
import com.example.zaixiantiku.entity.QuestionKnowledge;
import com.example.zaixiantiku.mapper.CourseTeacherMapper;
import com.example.zaixiantiku.mapper.PaperMapper;
import com.example.zaixiantiku.mapper.PaperQuestionMapper;
import com.example.zaixiantiku.mapper.QuestionKnowledgeMapper;
import com.example.zaixiantiku.mapper.QuestionMapper;
import com.example.zaixiantiku.pojo.dto.AutoGenerateRuleDTO;
import com.example.zaixiantiku.pojo.dto.PaperAutoGenerateDTO;
import com.example.zaixiantiku.pojo.dto.PaperQuestionDTO;
import com.example.zaixiantiku.pojo.dto.PaperSaveDTO;
import com.example.zaixiantiku.pojo.vo.PageResult;
import com.example.zaixiantiku.pojo.vo.PaperQuestionVO;
import com.example.zaixiantiku.pojo.vo.PaperVO;
import com.example.zaixiantiku.security.LoginUser;
import com.example.zaixiantiku.service.PaperService;
import com.github.pagehelper.PageHelper;
import com.github.pagehelper.PageInfo;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.Set;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class PaperServiceImpl implements PaperService {

    private final PaperMapper paperMapper;
    private final PaperQuestionMapper paperQuestionMapper;
    private final QuestionMapper questionMapper;
    private final QuestionKnowledgeMapper questionKnowledgeMapper;
    private final CourseTeacherMapper courseTeacherMapper;
    private final com.example.zaixiantiku.mapper.CourseMapper courseMapper;
    private final com.example.zaixiantiku.mapper.UserMapper userMapper;
    private final JdbcTemplate jdbcTemplate;

    @Override
    public PageResult<PaperVO> getPaperPage(Integer page, Integer size, String keyword, Long courseId, Integer status) {
        LoginUser loginUser = requireLoginUser();
        List<String> roles = loginUser.getRoleCodes();
        boolean isAdmin = roles != null && roles.contains("ADMIN");

        PageHelper.startPage(page, size);
        LambdaQueryWrapper<Paper> qw = new LambdaQueryWrapper<>();

        // 权限过滤：教师只能看到自己教授课程的试卷
        if (!isAdmin) {
            Long teacherId = loginUser.getUser().getId();
            List<Long> managedCourseIds = courseTeacherMapper.selectList(new LambdaQueryWrapper<CourseTeacher>()
                    .eq(CourseTeacher::getTeacherId, teacherId))
                    .stream().map(CourseTeacher::getCourseId).collect(Collectors.toList());
            if (managedCourseIds.isEmpty()) {
                return PageResult.of(0L, new ArrayList<>());
            }
            qw.in(Paper::getCourseId, managedCourseIds);
        }

        if (courseId != null) {
            qw.eq(Paper::getCourseId, courseId);
        }
        if (status != null) {
            qw.eq(Paper::getStatus, status);
        }
        if (StringUtils.hasText(keyword)) {
            qw.like(Paper::getPaperName, keyword);
        }
        qw.orderByDesc(Paper::getId);
        List<Paper> list = paperMapper.selectList(qw);
        PageInfo<Paper> pageInfo = new PageInfo<>(list);

        if (list.isEmpty()) {
            return PageResult.of(pageInfo.getTotal(), new ArrayList<>());
        }

        // 批量获取课程名和创建者名
        Set<Long> cIds = list.stream().map(Paper::getCourseId).collect(Collectors.toSet());
        Map<Long, String> courseMap = courseMapper.selectBatchIds(cIds).stream()
                .collect(Collectors.toMap(com.example.zaixiantiku.entity.Course::getId,
                        com.example.zaixiantiku.entity.Course::getCourseName));

        Set<Long> uIds = list.stream().map(Paper::getCreateBy).filter(java.util.Objects::nonNull)
                .collect(Collectors.toSet());
        Map<Long, String> userMap = new HashMap<>();
        if (!uIds.isEmpty()) {
            userMap = userMapper.selectBatchIds(uIds).stream()
                    .collect(Collectors.toMap(u -> u.getId(), u -> u.getName()));
        }

        final Map<Long, String> finalCourseMap = courseMap;
        final Map<Long, String> finalUserMap = userMap;
        List<PaperVO> voList = list.stream().map(p -> {
            PaperVO vo = toVO(p);
            vo.setCourseName(finalCourseMap.get(p.getCourseId()));
            vo.setCreatorName(finalUserMap.get(p.getCreateBy()));
            return vo;
        }).collect(Collectors.toList());

        return PageResult.of(pageInfo.getTotal(), voList);
    }

    @Override
    public PaperVO getPaperDetail(Long id) {
        Paper paper = paperMapper.selectById(id);
        if (paper == null) {
            throw new RuntimeException("试卷不存在");
        }
        LoginUser loginUser = requireLoginUser();
        requireTeacherOfCourseOrAdmin(loginUser, paper.getCourseId());

        PaperVO vo = toVO(paper);

        // 获取题目列表
        List<PaperQuestion> pqList = paperQuestionMapper.selectList(new LambdaQueryWrapper<PaperQuestion>()
                .eq(PaperQuestion::getPaperId, id)
                .orderByAsc(PaperQuestion::getSortOrder));

        if (!pqList.isEmpty()) {
            List<Long> qIds = pqList.stream().map(PaperQuestion::getQuestionId).collect(Collectors.toList());
            Map<Long, Question> qMap = questionMapper.selectBatchIds(qIds).stream()
                    .collect(Collectors.toMap(Question::getId, q -> q));

            List<PaperQuestionVO> qVoList = pqList.stream().map(pq -> {
                Question q = qMap.get(pq.getQuestionId());
                return PaperQuestionVO.builder()
                        .questionId(pq.getQuestionId())
                        .content(q != null ? q.getContent() : "[题目已删除]")
                        .score(pq.getScore())
                        .sortOrder(pq.getSortOrder())
                        .build();
            }).collect(Collectors.toList());
            vo.setQuestions(qVoList);
        } else {
            vo.setQuestions(new ArrayList<>());
        }

        return vo;
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public PaperVO createPaper(PaperSaveDTO saveDTO) {
        LoginUser loginUser = requireLoginUser();
        Long creatorId = loginUser.getUser().getId();
        requireTeacherOfCourseOrAdmin(loginUser, saveDTO.getCourseId());

        validatePaperName(saveDTO.getPaperName(), null, saveDTO.getCourseId());
        validatePaperScores(saveDTO);

        Paper paper = Paper.builder()
                .paperName(saveDTO.getPaperName())
                .courseId(saveDTO.getCourseId())
                .totalScore(saveDTO.getTotalScore())
                .remark(saveDTO.getRemark())
                .status(1)
                .createBy(creatorId)
                .build();

        paperMapper.insert(paper);

        if (saveDTO.getQuestions() != null) {
            for (PaperQuestionDTO q : saveDTO.getQuestions()) {
                PaperQuestion pq = PaperQuestion.builder()
                        .paperId(paper.getId())
                        .questionId(q.getQuestionId())
                        .score(q.getScore())
                        .sortOrder(q.getSortOrder())
                        .build();
                paperQuestionMapper.insert(pq);
            }
        }

        return toVO(paper);
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public PaperVO updatePaper(Long id, PaperSaveDTO saveDTO) {
        Paper paper = paperMapper.selectById(id);
        if (paper == null) {
            throw new RuntimeException("试卷不存在");
        }
        LoginUser loginUser = requireLoginUser();
        requireTeacherOfCourseOrAdmin(loginUser, paper.getCourseId());

        validatePaperName(saveDTO.getPaperName(), id, paper.getCourseId());
        validatePaperScores(saveDTO);

        paper.setPaperName(saveDTO.getPaperName());
        paper.setTotalScore(saveDTO.getTotalScore());
        paper.setRemark(saveDTO.getRemark());
        paperMapper.updateById(paper);

        // 更新题目关联：先删后增
        paperQuestionMapper.delete(new LambdaQueryWrapper<PaperQuestion>().eq(PaperQuestion::getPaperId, id));

        if (saveDTO.getQuestions() != null) {
            for (PaperQuestionDTO q : saveDTO.getQuestions()) {
                PaperQuestion pq = PaperQuestion.builder()
                        .paperId(id)
                        .questionId(q.getQuestionId())
                        .score(q.getScore())
                        .sortOrder(q.getSortOrder())
                        .build();
                paperQuestionMapper.insert(pq);
            }
        }

        return getPaperDetail(id);
    }

    private void validatePaperScores(PaperSaveDTO saveDTO) {
        if (saveDTO.getTotalScore() == null || saveDTO.getTotalScore() <= 0) {
            throw new RuntimeException("试卷总分必须大于0");
        }

        if (saveDTO.getQuestions() == null || saveDTO.getQuestions().isEmpty()) {
            throw new RuntimeException("试卷题目不能为空");
        }

        int questionCount = saveDTO.getQuestions().size();
        if (saveDTO.getTotalScore() < questionCount) {
            throw new RuntimeException("试卷总分(" + saveDTO.getTotalScore() + ")过小，每题至少1分，总分至少应为" + questionCount);
        }

        int sum = 0;
        for (PaperQuestionDTO q : saveDTO.getQuestions()) {
            if (q.getScore() == null || q.getScore() <= 0) {
                throw new RuntimeException("每道题目的分值必须大于0");
            }
            sum += q.getScore();
        }

        if (sum != saveDTO.getTotalScore()) {
            throw new RuntimeException("试卷总分(" + saveDTO.getTotalScore() + ")与各题分值总和(" + sum + ")不符");
        }
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public PaperVO autoGeneratePaper(PaperAutoGenerateDTO generateDTO) {
        LoginUser loginUser = requireLoginUser();
        Long creatorId = loginUser.getUser().getId();
        requireTeacherOfCourseOrAdmin(loginUser, generateDTO.getCourseId());

        validatePaperName(generateDTO.getPaperName(), null, generateDTO.getCourseId());

        AutoGenerateRuleDTO rule = generateDTO.getRule();
        if (rule == null || rule.getTypeDistribution() == null || rule.getTypeDistribution().isEmpty()) {
            throw new RuntimeException("组卷规则不能为空");
        }

        // 1. 获取所有可用题目并按类型分组
        Map<Integer, List<Question>> pool = new HashMap<>();
        Map<Long, Set<Long>> questionKnowledgeMap = new HashMap<>(); // questionId -> knowledgeIds

        for (AutoGenerateRuleDTO.TypeDistributionDTO dist : rule.getTypeDistribution()) {
            LambdaQueryWrapper<Question> qw = new LambdaQueryWrapper<>();
            qw.eq(Question::getCourseId, generateDTO.getCourseId());
            qw.eq(Question::getTypeId, dist.getTypeId());
            qw.eq(Question::getStatus, 2); // 已发布

            // 如果指定了知识点，先粗筛选（这一步是为了缩小搜索范围，GA会在这个范围内精选）
            // 注意：GA通常在符合基础约束的集合中搜索最优解
            List<Question> available = questionMapper.selectList(qw);
            if (available.size() < dist.getCount()) {
                throw new RuntimeException("题库中题型 [" + dist.getTypeId() + "] 数量不足，需要 " + dist.getCount() + " 题，现有 "
                        + available.size() + " 题");
            }
            pool.put(dist.getTypeId(), available);

            // 预加载知识点映射，用于计算适应度
            List<Long> qIds = available.stream().map(Question::getId).toList();
            if (!qIds.isEmpty()) {
                List<QuestionKnowledge> qks = questionKnowledgeMapper
                        .selectList(new LambdaQueryWrapper<QuestionKnowledge>()
                                .in(QuestionKnowledge::getQuestionId, qIds));
                for (QuestionKnowledge qk : qks) {
                    questionKnowledgeMap.computeIfAbsent(qk.getQuestionId(), k -> new HashSet<>())
                            .add(qk.getKnowledgePointId());
                }
            }
        }

        // 2. 运行遗传算法
        List<Question> bestQuestions = runGA(generateDTO, pool, questionKnowledgeMap);

        // 3. 持久化
        Paper paper = Paper.builder()
                .paperName(generateDTO.getPaperName())
                .courseId(generateDTO.getCourseId())
                .totalScore(generateDTO.getTotalScore())
                .status(1)
                .createBy(creatorId)
                .build();

        paperMapper.insert(paper);

        int sortOrder = 1;
        for (Question q : bestQuestions) {
            // 获取该题型在规则中定义的分值
            Integer score = rule.getTypeDistribution().stream()
                    .filter(d -> d.getTypeId().equals(q.getTypeId()))
                    .findFirst().map(AutoGenerateRuleDTO.TypeDistributionDTO::getScorePerQuestion).orElse(0);

            PaperQuestion pq = PaperQuestion.builder()
                    .paperId(paper.getId())
                    .questionId(q.getId())
                    .score(score)
                    .sortOrder(sortOrder++)
                    .build();
            paperQuestionMapper.insert(pq);
        }

        return toVO(paper);
    }

    private List<Question> runGA(PaperAutoGenerateDTO dto, Map<Integer, List<Question>> pool,
            Map<Long, Set<Long>> qkMap) {
        int populationSize = 30; // 种群大小
        int maxGenerations = 100; // 最大迭代次数
        double mutationRate = 0.1; // 变异率
        Random random = new Random();

        // 初始种群
        List<List<Question>> population = new ArrayList<>();
        for (int i = 0; i < populationSize; i++) {
            population.add(generateRandomIndividual(dto.getRule(), pool));
        }

        List<Question> bestIndividual = null;
        double bestFitness = -1;

        for (int gen = 0; gen < maxGenerations; gen++) {
            // 计算适应度
            List<Double> fitnessScores = new ArrayList<>();
            for (List<Question> individual : population) {
                double f = calculateFitness(individual, dto, qkMap);
                fitnessScores.add(f);
                if (f > bestFitness) {
                    bestFitness = f;
                    bestIndividual = new ArrayList<>(individual);
                }
            }

            // 如果已经找到完美解（适应度为1），提前结束
            if (bestFitness >= 0.99)
                break;

            // 选择 (轮盘赌)
            List<List<Question>> nextGeneration = new ArrayList<>();
            // 精英保留：保留上一代最好的
            nextGeneration.add(new ArrayList<>(bestIndividual));

            while (nextGeneration.size() < populationSize) {
                List<Question> parent1 = select(population, fitnessScores, random);
                List<Question> parent2 = select(population, fitnessScores, random);

                // 交叉
                List<Question> child = crossover(parent1, parent2, random);

                // 变异
                if (random.nextDouble() < mutationRate) {
                    mutate(child, pool, random);
                }

                nextGeneration.add(child);
            }
            population = nextGeneration;
        }

        return bestIndividual;
    }

    private List<Question> generateRandomIndividual(AutoGenerateRuleDTO rule, Map<Integer, List<Question>> pool) {
        List<Question> individual = new ArrayList<>();
        for (AutoGenerateRuleDTO.TypeDistributionDTO dist : rule.getTypeDistribution()) {
            List<Question> available = new ArrayList<>(pool.get(dist.getTypeId()));
            Collections.shuffle(available);
            for (int i = 0; i < dist.getCount(); i++) {
                individual.add(available.get(i));
            }
        }
        return individual;
    }

    private double calculateFitness(List<Question> individual, PaperAutoGenerateDTO dto, Map<Long, Set<Long>> qkMap) {
        AutoGenerateRuleDTO rule = dto.getRule();

        // 1. 难度系数偏差 (权重 0.4)
        double avgDifficulty = individual.stream().mapToInt(Question::getDifficulty).average().orElse(0);
        // 假设目标平均难度。如果用户没设比例，默认中等难度 2.0
        double targetDifficulty = 2.0;
        if (rule.getDifficultyRatio() != null && !rule.getDifficultyRatio().isEmpty()) {
            targetDifficulty = rule.getDifficultyRatio().entrySet().stream()
                    .mapToDouble(e -> Integer.parseInt(e.getKey()) * e.getValue()).sum();
        }
        double difficultyFitness = 1 - Math.abs(avgDifficulty - targetDifficulty) / 3.0;

        // 2. 知识点覆盖率 (权重 0.6)
        double knowledgeFitness = 0;
        if (rule.getKnowledgeIds() != null && !rule.getKnowledgeIds().isEmpty()) {
            Set<Long> targetIds = new HashSet<>(rule.getKnowledgeIds());
            Set<Long> coveredIds = new HashSet<>();
            for (Question q : individual) {
                Set<Long> qks = qkMap.get(q.getId());
                if (qks != null) {
                    for (Long kid : qks) {
                        if (targetIds.contains(kid))
                            coveredIds.add(kid);
                    }
                }
            }
            knowledgeFitness = (double) coveredIds.size() / targetIds.size();
        } else {
            knowledgeFitness = 1.0; // 没设要求则视为满分
        }

        return difficultyFitness * 0.4 + knowledgeFitness * 0.6;
    }

    private List<Question> select(List<List<Question>> population, List<Double> fitnessScores, Random random) {
        double totalFitness = fitnessScores.stream().mapToDouble(Double::doubleValue).sum();
        double slice = random.nextDouble() * totalFitness;
        double currentSum = 0;
        for (int i = 0; i < population.size(); i++) {
            currentSum += fitnessScores.get(i);
            if (currentSum >= slice)
                return population.get(i);
        }
        return population.get(0);
    }

    private List<Question> crossover(List<Question> p1, List<Question> p2, Random random) {
        // 由于有题型数量约束，简单的单点交叉会破坏约束。
        // 采用按题型分组交叉：随机决定某个题型从父1拿，还是从父2拿
        List<Question> child = new ArrayList<>();
        Set<Integer> typeIds = p1.stream().map(Question::getTypeId).collect(Collectors.toSet());

        for (Integer typeId : typeIds) {
            List<Question> typeP1 = p1.stream().filter(q -> q.getTypeId().equals(typeId)).toList();
            List<Question> typeP2 = p2.stream().filter(q -> q.getTypeId().equals(typeId)).toList();

            if (random.nextBoolean()) {
                child.addAll(typeP1);
            } else {
                child.addAll(typeP2);
            }
        }
        return child;
    }

    private void mutate(List<Question> individual, Map<Integer, List<Question>> pool, Random random) {
        // 随机选一个题型，更换其中一道题
        if (individual.isEmpty())
            return;
        int idx = random.nextInt(individual.size());
        Question oldQ = individual.get(idx);
        List<Question> available = pool.get(oldQ.getTypeId());

        // 选一道不在当前个体中的题
        Set<Long> currentIds = individual.stream().map(Question::getId).collect(Collectors.toSet());
        List<Question> candidates = available.stream().filter(q -> !currentIds.contains(q.getId())).toList();

        if (!candidates.isEmpty()) {
            individual.set(idx, candidates.get(random.nextInt(candidates.size())));
        }
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public void deletePaper(Long id) {
        Paper paper = paperMapper.selectById(id);
        if (paper == null) {
            return;
        }
        LoginUser loginUser = requireLoginUser();
        requireTeacherOfCourseOrAdmin(loginUser, paper.getCourseId());

        // 检查是否被考试引用
        Integer count = jdbcTemplate.queryForObject("SELECT COUNT(1) FROM exam WHERE paper_id = ?",
                Integer.class, id);
        if (count != null && count > 0) {
            throw new RuntimeException("试卷已被考试引用，禁止删除");
        }

        paperMapper.deleteById(id);
        // paper_question 会通过数据库外键级联删除 (ON DELETE CASCADE)
    }

    private void validatePaperName(String name, Long id, Long courseId) {
        if (!StringUtils.hasText(name)) {
            throw new RuntimeException("试卷名称不能为空");
        }
        LambdaQueryWrapper<Paper> qw = new LambdaQueryWrapper<>();
        qw.eq(Paper::getPaperName, name.trim());
        qw.eq(Paper::getCourseId, courseId);
        if (id != null) {
            qw.ne(Paper::getId, id);
        }
        if (paperMapper.selectCount(qw) > 0) {
            throw new RuntimeException("试卷名称 [" + name + "] 在该课程下已存在");
        }
    }

    private PaperVO toVO(Paper paper) {
        return PaperVO.builder()
                .id(paper.getId())
                .paperName(paper.getPaperName())
                .courseId(paper.getCourseId())
                .totalScore(paper.getTotalScore())
                .remark(paper.getRemark())
                .status(paper.getStatus())
                .createBy(paper.getCreateBy())
                .createTime(paper.getCreateTime())
                .updateTime(paper.getUpdateTime())
                .build();
    }

    private LoginUser requireLoginUser() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication == null || !authentication.isAuthenticated()) {
            throw new RuntimeException("未登录");
        }
        Object principal = authentication.getPrincipal();
        if (principal instanceof LoginUser loginUser) {
            return loginUser;
        }
        throw new RuntimeException("未登录");
    }

    private void requireTeacherOfCourseOrAdmin(LoginUser loginUser, Long courseId) {
        List<String> roles = loginUser.getRoleCodes();
        if (roles != null && roles.contains("ADMIN")) {
            return;
        }
        if (roles == null || !roles.contains("TEACHER")) {
            throw new RuntimeException("没有权限操作");
        }
        Long teacherId = loginUser.getUser().getId();
        Long count = courseTeacherMapper.selectCount(new LambdaQueryWrapper<CourseTeacher>()
                .eq(CourseTeacher::getCourseId, courseId)
                .eq(CourseTeacher::getTeacherId, teacherId));
        if (count == null || count <= 0) {
            throw new RuntimeException("没有权限操作该课程");
        }
    }
}
