package com.example.zaixiantiku.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.example.zaixiantiku.entity.Course;
import com.example.zaixiantiku.entity.CourseTeacher;
import com.example.zaixiantiku.entity.Paper;
import com.example.zaixiantiku.entity.PaperQuestion;
import com.example.zaixiantiku.entity.Question;
import com.example.zaixiantiku.entity.QuestionKnowledge;
import com.example.zaixiantiku.mapper.CourseMapper;
import com.example.zaixiantiku.mapper.CourseTeacherMapper;
import com.example.zaixiantiku.mapper.PaperMapper;
import com.example.zaixiantiku.mapper.PaperQuestionMapper;
import com.example.zaixiantiku.mapper.QuestionKnowledgeMapper;
import com.example.zaixiantiku.mapper.QuestionMapper;
import com.example.zaixiantiku.pojo.dto.AutoGenerateRuleDTO;
import com.example.zaixiantiku.pojo.dto.PaperAutoGenerateDTO;
import com.example.zaixiantiku.pojo.dto.PaperQuestionDTO;
import com.example.zaixiantiku.pojo.dto.PaperSaveDTO;
import com.example.zaixiantiku.pojo.vo.PageResult;
import com.example.zaixiantiku.pojo.vo.PaperQuestionVO;
import com.example.zaixiantiku.pojo.vo.PaperVO;
import com.example.zaixiantiku.security.LoginUser;
import com.example.zaixiantiku.service.PaperService;
import com.github.pagehelper.PageHelper;
import com.github.pagehelper.PageInfo;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class PaperServiceImpl implements PaperService {

    private final PaperMapper paperMapper;
    private final PaperQuestionMapper paperQuestionMapper;
    private final QuestionMapper questionMapper;
    private final QuestionKnowledgeMapper questionKnowledgeMapper;
    private final CourseMapper courseMapper;
    private final CourseTeacherMapper courseTeacherMapper;
    private final JdbcTemplate jdbcTemplate;

    @Override
    public PageResult<PaperVO> getPaperPage(Integer page, Integer size, String keyword, Long courseId, Integer status) {
        PageHelper.startPage(page, size);
        LambdaQueryWrapper<Paper> qw = new LambdaQueryWrapper<>();
        if (courseId != null) {
            qw.eq(Paper::getCourseId, courseId);
        }
        if (status != null) {
            qw.eq(Paper::getStatus, status);
        }
        if (StringUtils.hasText(keyword)) {
            qw.like(Paper::getPaperName, keyword);
        }
        qw.orderByDesc(Paper::getId);
        List<Paper> list = paperMapper.selectList(qw);
        PageInfo<Paper> pageInfo = new PageInfo<>(list);
        List<PaperVO> voList = list.stream().map(this::toVO).collect(Collectors.toList());
        return PageResult.of(pageInfo.getTotal(), voList);
    }

    @Override
    public PaperVO getPaperDetail(Long id) {
        Paper paper = paperMapper.selectById(id);
        if (paper == null) {
            throw new RuntimeException("试卷不存在");
        }
        PaperVO vo = toVO(paper);

        // 获取题目列表
        List<PaperQuestion> pqList = paperQuestionMapper.selectList(new LambdaQueryWrapper<PaperQuestion>()
                .eq(PaperQuestion::getPaperId, id)
                .orderByAsc(PaperQuestion::getSortOrder));

        if (!pqList.isEmpty()) {
            List<Long> qIds = pqList.stream().map(PaperQuestion::getQuestionId).collect(Collectors.toList());
            Map<Long, Question> qMap = questionMapper.selectBatchIds(qIds).stream()
                    .collect(Collectors.toMap(Question::getId, q -> q));

            List<PaperQuestionVO> qVoList = pqList.stream().map(pq -> {
                Question q = qMap.get(pq.getQuestionId());
                return PaperQuestionVO.builder()
                        .questionId(pq.getQuestionId())
                        .content(q != null ? q.getContent() : "[题目已删除]")
                        .score(pq.getScore())
                        .sortOrder(pq.getSortOrder())
                        .build();
            }).collect(Collectors.toList());
            vo.setQuestions(qVoList);
        } else {
            vo.setQuestions(new ArrayList<>());
        }

        return vo;
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public PaperVO createPaper(PaperSaveDTO saveDTO) {
        LoginUser loginUser = requireLoginUser();
        Long creatorId = loginUser.getUser().getId();
        requireTeacherOfCourseOrAdmin(loginUser, saveDTO.getCourseId());

        validatePaperName(saveDTO.getPaperName(), null, saveDTO.getCourseId());

        Paper paper = Paper.builder()
                .paperName(saveDTO.getPaperName())
                .courseId(saveDTO.getCourseId())
                .totalScore(saveDTO.getTotalScore())
                .remark(saveDTO.getRemark())
                .status(1)
                .createBy(creatorId)
                .build();

        paperMapper.insert(paper);

        if (saveDTO.getQuestions() != null) {
            for (PaperQuestionDTO q : saveDTO.getQuestions()) {
                PaperQuestion pq = PaperQuestion.builder()
                        .paperId(paper.getId())
                        .questionId(q.getQuestionId())
                        .score(q.getScore())
                        .sortOrder(q.getSortOrder())
                        .build();
                paperQuestionMapper.insert(pq);
            }
        }

        return toVO(paper);
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public PaperVO updatePaper(Long id, PaperSaveDTO saveDTO) {
        Paper paper = paperMapper.selectById(id);
        if (paper == null) {
            throw new RuntimeException("试卷不存在");
        }
        LoginUser loginUser = requireLoginUser();
        requireTeacherOfCourseOrAdmin(loginUser, paper.getCourseId());

        validatePaperName(saveDTO.getPaperName(), id, paper.getCourseId());

        paper.setPaperName(saveDTO.getPaperName());
        paper.setTotalScore(saveDTO.getTotalScore());
        paper.setRemark(saveDTO.getRemark());
        paperMapper.updateById(paper);

        // 更新题目关联：先删后增
        paperQuestionMapper.delete(new LambdaQueryWrapper<PaperQuestion>().eq(PaperQuestion::getPaperId, id));

        if (saveDTO.getQuestions() != null) {
            for (PaperQuestionDTO q : saveDTO.getQuestions()) {
                PaperQuestion pq = PaperQuestion.builder()
                        .paperId(id)
                        .questionId(q.getQuestionId())
                        .score(q.getScore())
                        .sortOrder(q.getSortOrder())
                        .build();
                paperQuestionMapper.insert(pq);
            }
        }

        return getPaperDetail(id);
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public PaperVO autoGeneratePaper(PaperAutoGenerateDTO generateDTO) {
        LoginUser loginUser = requireLoginUser();
        Long creatorId = loginUser.getUser().getId();
        requireTeacherOfCourseOrAdmin(loginUser, generateDTO.getCourseId());

        validatePaperName(generateDTO.getPaperName(), null, generateDTO.getCourseId());

        AutoGenerateRuleDTO rule = generateDTO.getRule();
        List<PaperQuestionDTO> selectedQuestions = new ArrayList<>();
        int currentSortOrder = 1;

        if (rule != null && rule.getTypeDistribution() != null) {
            for (AutoGenerateRuleDTO.TypeDistributionDTO dist : rule.getTypeDistribution()) {
                LambdaQueryWrapper<Question> qw = new LambdaQueryWrapper<>();
                qw.eq(Question::getCourseId, generateDTO.getCourseId());
                qw.eq(Question::getTypeId, dist.getTypeId());
                qw.eq(Question::getStatus, 2); // 已发布

                if (rule.getKnowledgeIds() != null && !rule.getKnowledgeIds().isEmpty()) {
                    List<Long> questionIdsInKnowledge = questionKnowledgeMapper.selectList(
                            new LambdaQueryWrapper<QuestionKnowledge>()
                                    .in(QuestionKnowledge::getKnowledgePointId, rule.getKnowledgeIds()))
                            .stream().map(QuestionKnowledge::getQuestionId).distinct().collect(Collectors.toList());

                    if (questionIdsInKnowledge.isEmpty()) {
                        continue;
                    }
                    qw.in(Question::getId, questionIdsInKnowledge);
                }

                List<Question> availableQuestions = questionMapper.selectList(qw);

                // 难度过滤 (简单逻辑：如果指定了难度比例，则在对应难度中随机选)
                // 这里为了简化，我们先取所有符合条件的题目，然后根据难度分布随机打乱后选取
                Collections.shuffle(availableQuestions);

                int count = Math.min(dist.getCount(), availableQuestions.size());
                for (int i = 0; i < count; i++) {
                    Question q = availableQuestions.get(i);
                    PaperQuestionDTO pqDto = new PaperQuestionDTO();
                    pqDto.setQuestionId(q.getId());
                    pqDto.setScore(dist.getScorePerQuestion());
                    pqDto.setSortOrder(currentSortOrder++);
                    selectedQuestions.add(pqDto);
                }
            }
        }

        Paper paper = Paper.builder()
                .paperName(generateDTO.getPaperName())
                .courseId(generateDTO.getCourseId())
                .totalScore(generateDTO.getTotalScore())
                .status(1)
                .createBy(creatorId)
                .build();

        paperMapper.insert(paper);

        for (PaperQuestionDTO q : selectedQuestions) {
            PaperQuestion pq = PaperQuestion.builder()
                    .paperId(paper.getId())
                    .questionId(q.getQuestionId())
                    .score(q.getScore())
                    .sortOrder(q.getSortOrder())
                    .build();
            paperQuestionMapper.insert(pq);
        }

        return toVO(paper);
    }

    @Override
    @Transactional(rollbackFor = Exception.class)
    public void deletePaper(Long id) {
        Paper paper = paperMapper.selectById(id);
        if (paper == null) {
            return;
        }
        LoginUser loginUser = requireLoginUser();
        requireTeacherOfCourseOrAdmin(loginUser, paper.getCourseId());

        // 检查是否被考试引用
        if (existsTable("exam_paper")) {
            Integer count = jdbcTemplate.queryForObject("SELECT COUNT(1) FROM exam_paper WHERE paper_id = ?",
                    Integer.class, id);
            if (count != null && count > 0) {
                throw new RuntimeException("试卷已被考试引用，禁止删除");
            }
        }

        paperMapper.deleteById(id);
        // paper_question 会通过数据库外键级联删除 (ON DELETE CASCADE)
    }

    private boolean existsTable(String tableName) {
        Integer c = jdbcTemplate.queryForObject(
                "SELECT COUNT(1) FROM information_schema.tables WHERE table_schema = DATABASE() AND table_name = ?",
                Integer.class,
                tableName);
        return c != null && c > 0;
    }

    private void validatePaperName(String name, Long id, Long courseId) {
        if (!StringUtils.hasText(name)) {
            throw new RuntimeException("试卷名称不能为空");
        }
        LambdaQueryWrapper<Paper> qw = new LambdaQueryWrapper<>();
        qw.eq(Paper::getPaperName, name.trim());
        qw.eq(Paper::getCourseId, courseId);
        if (id != null) {
            qw.ne(Paper::getId, id);
        }
        if (paperMapper.selectCount(qw) > 0) {
            throw new RuntimeException("试卷名称 [" + name + "] 在该课程下已存在");
        }
    }

    private PaperVO toVO(Paper paper) {
        return PaperVO.builder()
                .id(paper.getId())
                .paperName(paper.getPaperName())
                .courseId(paper.getCourseId())
                .totalScore(paper.getTotalScore())
                .remark(paper.getRemark())
                .status(paper.getStatus())
                .createBy(paper.getCreateBy())
                .createTime(paper.getCreateTime())
                .updateTime(paper.getUpdateTime())
                .build();
    }

    private LoginUser requireLoginUser() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication == null || !authentication.isAuthenticated()) {
            throw new RuntimeException("未登录");
        }
        Object principal = authentication.getPrincipal();
        if (principal instanceof LoginUser loginUser) {
            return loginUser;
        }
        throw new RuntimeException("未登录");
    }

    private void requireTeacherOfCourseOrAdmin(LoginUser loginUser, Long courseId) {
        List<String> roles = loginUser.getRoleCodes();
        if (roles != null && roles.contains("ADMIN")) {
            return;
        }
        if (roles == null || !roles.contains("TEACHER")) {
            throw new RuntimeException("没有权限操作");
        }
        Long teacherId = loginUser.getUser().getId();
        Long count = courseTeacherMapper.selectCount(new LambdaQueryWrapper<CourseTeacher>()
                .eq(CourseTeacher::getCourseId, courseId)
                .eq(CourseTeacher::getTeacherId, teacherId));
        if (count == null || count <= 0) {
            throw new RuntimeException("没有权限操作该课程");
        }
    }
}
